language: bash
sudo: required

services:
      - docker

dist: trusty

matrix:
    include:
        - os: osx
          osx_image: xcode9.1
script: 
    - sudo ./setup-macos.sh

git:
    submodules: false
