---
- hosts: all
  tags: [macos, linux]
  tasks:
  - name: get TPM
    git:
      repo: https://github.com/tmux-plugins/tpm
      dest: ~/.tmux/plugins/tpm

  - file: path=~/bin state=directory mode=0755

  - file: path=~/workspace state=directory mode=0755

  - name: get luan vimfiles
    git:
      repo: https://github.com/luan/vimfiles
      dest: ~/.luanvimfiles

  - name: installs luan vimfiles
    command: ~/.luanvimfiles/install

  - name: install python support for nvim
    command: pip3 install --user --upgrade pynvim

  - name: set up user symlinks
    file:
      path: "{{item.target}}"
      src: "{{item.src}}"
      state: link
      force: yes
    with_items:
    - {target: ~/.source, src: "{{ansible_env.PWD}}/config/source"}
    - {target: ~/.gitconfig-shared, src: "{{ansible_env.PWD}}/config/.gitconfig-shared"}
    - {target: ~/.gitignore, src: "{{ansible_env.PWD}}/config/.gitignore"}
    - {target: ~/.ssh/rc, src: "{{ansible_env.PWD}}/executables/ssh.rc"}
    - {target: ~/.tmux.conf, src: "{{ansible_env.PWD}}/config/tmux.conf"}
    - {target: ~/.zshrc, src: "{{ansible_env.PWD}}/config/zshrc"}
    - {target: ~/bin/load-personal-keys, src: "{{ansible_env.PWD}}/executables/load-personal-keys"}
    - {target: ~/bin/ensure-lpass-logged-in, src: "{{ansible_env.PWD}}/executables/ensure-lpass-logged-in"}
  - name: ~/.gitconfig
    blockinfile:
      path: ~/.gitconfig
      create: yes
      block: |
        [include]
          path = ~/.gitconfig-shared
